### ISSUE TITLE
Model: MovieList

### ISSUE THREAD

**Issue by LoganSmith99** [tllyon79/My-Movie-Library#10]
Movie List is a class that contains a list of movies and is used to create filtered search results for both the movie library and wishlists.

Attributes:
- List\<Movie\> Movies

Methods: 
- [x] sort
- [x] filter
- [x] view

Dependencies:
#8

**Comment by callistutts** [comment]
> Movie List is a class that contains a list of movies and is used to create filtered search results for both the movie library and wishlists.
> 
> Attributes:
> 
>     * List<Movie> Movies
> 
> 
> Methods:
> 
>     * [ ]  sort
> 
>     * [ ]  filter
>
for filter and sort we discussed a more global method under the "search" model. 


>     * [ ]  view
> 
> 
> Dependencies: #8
